export const authConstant = {
    SIGNIN_REQUEST: "SIGNIN_REQUEST",
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNIN_FAILURE: "SIGNIN_FAILURE",

    SIGNOUT_REQUEST: "SIGNOUT_REQUEST",
    SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
    SIGNOUT_FAILURE: "SIGNOUT_FAILURE",

    CLEAR_LOGIN_SIGNUP_ERROR: "CLEAR_LOGIN_SIGNUP_ERROR",
    CLEAR_LOGIN_SIGNUP_SUCCESS: "CLEAR_LOGIN_SIGNUP_SUCCESS",
}