export const departmentConstant = {
    DEPARTMENT_LIST_REQUEST : "DEPARTMENT_LIST_REQUEST",
    DEPARTMENT_LIST_SUCCESS : "DEPARTMENT_LIST_SUCCESS",
    DEPARTMENT_LIST_FAILURE : "DEPARTMENT_LIST_FAILURE",
}