export const departmentConstant = {
    DEPARTMENT_LIST_REQUEST: "DEPARTMENT_LIST_REQUEST",
    DEPARTMENT_LIST_SUCCESS: "DEPARTMENT_LIST_SUCCESS",
    DEPARTMENT_LIST_FAILURE: "DEPARTMENT_LIST_FAILURE",

    DEPARTMENT_ADD_REQUEST: "DEPARTMENT_ADD_REQUEST",
    DEPARTMENT_ADD_SUCCESS: "DEPARTMENT_ADD_SUCCESS",
    DEPARTMENT_ADD_FAILURE: "DEPARTMENT_ADD_FAILURE",

    DEPARTMENT_EDIT_DETAILS_REQUEST: "DEPARTMENT_EDIT_DETAILS_REQUEST",
    DEPARTMENT_EDIT_DETAILS_SUCCESS: "DEPARTMENT_EDIT_DETAILS_SUCCESS",
    DEPARTMENT_EDIT_DETAILS_FAILURE: "DEPARTMENT_EDIT_DETAILS_FAILURE",

    DEPARTMENT_EDIT_REQUEST: "DEPARTMENT_EDIT_REQUEST",
    DEPARTMENT_EDIT_SUCCESS: "DEPARTMENT_EDIT_SUCCESS",
    DEPARTMENT_EDIT_FAILURE: "DEPARTMENT_EDIT_FAILURE",
}