export const employeeConstant = {
    EMPLOYEE_LIST_REQUEST: "EMPLOYEE_LIST_REQUEST",
    EMPLOYEE_LIST_SUCCESS: "EMPLOYEE_LIST_SUCCESS",
    EMPLOYEE_LIST_FAILURE: "EMPLOYEE_LIST_FAILURE",

    EMPLOYEE_ADD_REQUEST: "EMPLOYEE_ADD_REQUEST",
    EMPLOYEE_ADD_SUCCESS: "EMPLOYEE_ADD_SUCCESS",
    EMPLOYEE_ADD_FAILURE: "EMPLOYEE_ADD_FAILURE",

    EMPLOYEE_EDIT_DETAILS_REQUEST: "EMPLOYEE_EDIT_DETAILS_REQUEST",
    EMPLOYEE_EDIT_DETAILS_SUCCESS: "EMPLOYEE_EDIT_DETAILS_SUCCESS",
    EMPLOYEE_EDIT_DETAILS_FAILURE: "EMPLOYEE_EDIT_DETAILS_FAILURE",

    EMPLOYEE_EDIT_REQUEST: "EMPLOYEE_EDIT_REQUEST",
    EMPLOYEE_EDIT_SUCCESS: "EMPLOYEE_EDIT_SUCCESS",
    EMPLOYEE_EDIT_FAILURE: "EMPLOYEE_EDIT_FAILURE",
}